[package]
  edition.workspace = true
  name              = "novelsaga-android"
  version.workspace = true

[lib]
  crate-type = ["cdylib"]

[dependencies]
  novelsaga-core = { path = "../core" }

[lints]
  workspace = true
